// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRUs93_N1mbx3D1RkmiSam0kBZAqE1nQo',
    appId: '1:953258127316:web:1f61a12ee227b3438d3041',
    messagingSenderId: '953258127316',
    projectId: 'belanjaku-9f2c9',
    authDomain: 'belanjaku-9f2c9.firebaseapp.com',
    storageBucket: 'belanjaku-9f2c9.appspot.com',
    measurementId: 'G-3HW63P0QZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI0WVw2tHLfSwcrYicgJ-kF6D8Nm8CPOE',
    appId: '1:953258127316:android:793b76a93e41a5378d3041',
    messagingSenderId: '953258127316',
    projectId: 'belanjaku-9f2c9',
    storageBucket: 'belanjaku-9f2c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9GBBju7aCrqQKD1rt9k8oMokbELnqUw',
    appId: '1:953258127316:ios:6461c79b80f1367a8d3041',
    messagingSenderId: '953258127316',
    projectId: 'belanjaku-9f2c9',
    storageBucket: 'belanjaku-9f2c9.appspot.com',
    iosClientId: '953258127316-air9rtm5h8e32q56jp0dsheu40dh2l9v.apps.googleusercontent.com',
    iosBundleId: 'com.gue.shindu.belanjaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj9GBBju7aCrqQKD1rt9k8oMokbELnqUw',
    appId: '1:953258127316:ios:6461c79b80f1367a8d3041',
    messagingSenderId: '953258127316',
    projectId: 'belanjaku-9f2c9',
    storageBucket: 'belanjaku-9f2c9.appspot.com',
    iosClientId: '953258127316-air9rtm5h8e32q56jp0dsheu40dh2l9v.apps.googleusercontent.com',
    iosBundleId: 'com.gue.shindu.belanjaku',
  );
}
